import type { Schema } from "@t8/sdk-factory";
import type { ClearTrash } from "./methods/ClearTrash.ts";
import type { CopyResource } from "./methods/CopyResource.ts";
import type { CreateResource } from "./methods/CreateResource.ts";
import type { DownloadPublicResource } from "./methods/DownloadPublicResource.ts";
import type { DownloadResource } from "./methods/DownloadResource.ts";
import type { GetDisk } from "./methods/GetDisk.ts";
import type { GetFlatFileList } from "./methods/GetFlatFileList.ts";
import type { GetLastUploaded } from "./methods/GetLastUploaded.ts";
import type { GetOperation } from "./methods/GetOperation.ts";
import type { GetPublicResource } from "./methods/GetPublicResource.ts";
import type { GetPublicResources } from "./methods/GetPublicResources.ts";
import type { GetResource } from "./methods/GetResource.ts";
import type { MoveResource } from "./methods/MoveResource.ts";
import type { PublishResource } from "./methods/PublishResource.ts";
import type { RemoveResource } from "./methods/RemoveResource.ts";
import type { RestoreFromTrash } from "./methods/RestoreFromTrash.ts";
import type { SaveToDisk } from "./methods/SaveToDisk.ts";
import type { SetCustomProperties } from "./methods/SetCustomProperties.ts";
import type { UnpublishResource } from "./methods/UnpublishResource.ts";
import type { UploadRemoteResource } from "./methods/UploadRemoteResource.ts";
import type { UploadResource } from "./methods/UploadResource.ts";

export type APISchema = Schema<{
  "GET /disk": GetDisk;
  "GET /disk/resources/files": GetFlatFileList;
  "GET /disk/resources/last-uploaded": GetLastUploaded;
  "GET /disk/resources": GetResource;
  "GET /disk/resources/public": GetPublicResources;
  "GET /disk/public/resources": GetPublicResource;
  "GET /disk/public/resources/download": DownloadPublicResource;
  "POST /disk/public/resources/save-to-disk": SaveToDisk;
  "PUT /disk/resources/publish": PublishResource;
  "PUT /disk/resources/unpublish": UnpublishResource;
  "POST /disk/resources/copy": CopyResource;
  "POST /disk/resources/move": MoveResource;
  "DELETE /disk/resources": RemoveResource;
  "PUT /disk/resources": CreateResource;
  "GET /disk/resources/upload": UploadResource;
  "POST /disk/resources/upload": UploadRemoteResource;
  "GET /disk/resources/download": DownloadResource;
  "PATCH /disk/resources": SetCustomProperties;
  "GET /disk/operations": GetOperation;
  "DELETE /disk/trash/resources": ClearTrash;
  "PUT /disk/trash/resources/restore": RestoreFromTrash;
}>;
